import { useCallback, useEffect, useState } from 'react';
import { FileUp, RefreshCw, Play, Pause, ArrowRight, FileText } from 'lucide-react';
import { api, date, setCsrf, type Session } from './api';
import { Shell, SignIn, Stat, Badge, Empty, Notice } from './ui';

type Job={id:string;source_name:string;status:string;attempts:number;accepted:number;rejected:number;duplicates:number;error:string|null;created_at:string;finished_at:string|null;duration_ms:number};
type Detail=Job&{rejections:{row_number:number;reason:string;raw_row:Record<string,string>}[]};
type Data={jobs:Job[];summary:{readings:number;vehicles:number;last_success:string|null;failed_jobs:number};schedule:{enabled:boolean;interval_seconds:number;last_tick:string|null;next_run:string};readings:{reading_id:string;vehicle_id:string;recorded_at:string;miles:number;fuel_gallons:number}[]};

export default function App(){
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);
  const [data,setData]=useState<Data|null>(null),[detail,setDetail]=useState<Detail|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState('Imports');
  const [file,setFile]=useState<File|null>(null);
  const refresh=useCallback(async()=>{setData(await api<Data>('/dashboard'));},[]);
  useEffect(()=>{api<Session>('/session').then(s=>{setSession(s);setCsrf(s.csrf);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(!session?.user)return;refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),4000);return()=>clearInterval(timer);},[session,refresh]);
  useEffect(()=>{if(!detail||!['running','queued'].includes(detail.status))return;const timer=setTimeout(()=>api<Detail>(`/jobs/${detail.id}`).then(setDetail).catch(e=>setError(e.message)),3000);return()=>clearTimeout(timer);},[detail]);
  async function act(work:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await work();await refresh();setMessage(success);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(loading)return <div className="empty">Opening Import Desk...</div>;
  if(!session?.user)return <SignIn index={1} onLogin={setSession}/>;
  return <Shell index={1} user={session.user} onLogout={()=>{api('/logout',{}).then(()=>setSession(null)).catch(e=>setError(e.message));}}><div className="content"><div className="page-heading"><div><span className="eyebrow">EVERY ROW HAS A STORY</span><h1>Know what made it through.</h1><p>Fleet imports, checked before they reach your reports.</p></div><div className="buttons"><button disabled={busy} onClick={()=>act(refresh,'Up to date.')}><RefreshCw size={14}/>Refresh</button><button className="primary" disabled={busy} onClick={()=>act(async()=>{const r=await api<{id:string;reused:boolean}>('/sample',{});setDetail(await api<Detail>(`/jobs/${r.id}`));setTab('Imports');},'Sample file opened. Its import will run in the background.')}><Play size={14}/>Try sample import</button></div></div><Notice error={error} message={message}/>
    <div className="stats"><Stat label="Saved readings" value={data?.summary.readings??0} note="Unique records in the database"/><Stat label="Vehicles" value={data?.summary.vehicles??0} note="Represented in saved readings"/><Stat label="Last successful import" value={<span className="text-stat">{date(data?.summary.last_success??null)}</span>} note="Includes imports with rejected rows"/><Stat label="Failed jobs" value={data?.summary.failed_jobs??0} note="Open a job to review or retry"/></div>
    <div className="tabs" role="tablist" aria-label="Import sections">{['Imports','Saved readings','Schedule'].map(t=><button role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
    {tab==='Imports'&&<div className="split"><div><section className="panel"><div className="panel-header"><div><h2>Import history</h2><p>Updates every four seconds while this page is open.</p></div><span className="count">{data?.jobs.length??0} recent jobs</span></div>{!data?.jobs.length?<Empty title="Ready for your first file">Try the sample to see valid rows, duplicates, and a few mistakes.</Empty>:<div className="table-wrap"><table><thead><tr><th>Source</th><th>Status</th><th>Saved</th><th>Rejected</th><th/></tr></thead><tbody>{data.jobs.map(job=><tr key={job.id}><td><strong>{job.source_name}</strong><small>{date(job.created_at)}</small></td><td><Badge value={job.status}/></td><td>{job.accepted}</td><td>{job.rejected}</td><td><button className="small" aria-label={`Review ${job.source_name}`} onClick={()=>act(async()=>setDetail(await api<Detail>(`/jobs/${job.id}`)),'')}>Review<ArrowRight size={12}/></button></td></tr>)}</tbody></table></div>}</section>
      {detail&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">IMPORT DETAILS</span><h2>{detail.source_name}</h2></div><Badge value={detail.status}/></div><p className="muted">{detail.accepted} saved · {detail.duplicates} duplicates · {detail.rejected} rejected · Attempt {detail.attempts} · {detail.duration_ms??0} ms</p>{detail.error&&<Notice error={detail.error}/>}<div className="buttons"><a className="text-button" href={`/api/jobs/${detail.id}/raw`}>Download original CSV</a>{detail.status==='failed'&&<button disabled={busy} className="small" onClick={()=>act(async()=>{await api(`/jobs/${detail.id}/retry`,{});setDetail(await api<Detail>(`/jobs/${detail.id}`));},'Import queued for another attempt.')}>Retry import</button>}</div><div className="divider"/>{detail.rejections.length?detail.rejections.map(row=><div className="activity" key={row.row_number}><span className="badge rejected">Row {row.row_number}</span><div><h3>{row.reason}</h3><p className="mono">{Object.entries(row.raw_row).map(([key,value])=>`${key}: ${value||'(empty)'}`).join(' · ')}</p></div></div>):<p className="muted">{['queued','running'].includes(detail.status)?'The worker is still processing this file.':'No rejected rows in this import.'}</p>}</section>}</div>
      <aside><form className="panel" onSubmit={e=>{e.preventDefault();if(!file)return;act(async()=>{if(file.size>1_000_000)throw new Error('Choose a CSV smaller than 1 MB.');const r=await api<{id:string;reused:boolean}>('/imports',{name:file.name,csv:await file.text()});setDetail(await api<Detail>(`/jobs/${r.id}`));},'File accepted. An identical file will reuse its existing import.');}}><FileUp size={25} style={{color:'var(--accent)',marginBottom:14}}/><h2>Bring in a CSV</h2><p className="muted">Keep the original file and get a clear report of anything that needs fixing.</p><label>CSV file<input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]??null)} required/></label><button className="primary" disabled={busy||!file}><FileUp size={14}/>Queue import</button><div className="subtle-box"><p>Required columns, in order:<br/><span className="mono">reading_id, vehicle_id,<br/>recorded_at, miles, fuel_gallons</span></p></div><p className="tiny">UTF-8 CSV · Up to 1 MB · 10,000 rows<br/>Dates need a time zone. Numbers can have up to two decimal places.</p></form><section className="panel"><FileText size={21}/><h3 style={{marginTop:12}}>Fix the row, keep the record</h3><p className="muted">Bad rows stay in the import report. Correct them in a new file, then upload it. Previously saved readings are not added twice.</p></section></aside></div>}
    {tab==='Saved readings'&&<section className="panel"><div className="panel-header"><div><h2>Clean records</h2><p>The 25 most recently imported readings. All data here is sample data unless you upload your own.</p></div></div><div className="table-wrap"><table><thead><tr><th>Reading</th><th>Vehicle</th><th>Recorded</th><th>Miles</th><th>Fuel / gal</th></tr></thead><tbody>{data?.readings.map(r=><tr key={r.reading_id}><td className="mono">{r.reading_id}</td><td>{r.vehicle_id}</td><td>{date(r.recorded_at)}</td><td>{Number(r.miles).toFixed(1)}</td><td>{Number(r.fuel_gallons).toFixed(1)}</td></tr>)}</tbody></table></div>{!data?.readings.length&&<Empty title="No readings saved yet"/>}</section>}
    {tab==='Schedule'&&<section className="panel"><div className="panel-header"><div><h2>Scheduled sample feed</h2><p>A separate worker imports a generated reading every five minutes.</p></div><Badge value={data?.schedule.enabled?'running':'paused'}/></div><p className="muted">Worker last checked: {date(data?.schedule.last_tick??null)}</p><p className="muted">Next scheduled run: {data?.schedule.enabled?date(data.schedule.next_run):'Paused'}</p><button disabled={busy} className="primary" onClick={()=>act(()=>api('/schedule',{enabled:!data?.schedule.enabled,interval_seconds:300}),'Schedule updated.')}>{data?.schedule.enabled?<Pause size={14}/>:<Play size={14}/>} {data?.schedule.enabled?'Pause sample feed':'Resume sample feed'}</button><div className="subtle-box"><p>The worker must be running for scheduled imports. After a restart, it picks up queued jobs. A job left running for more than five minutes can be recovered.</p></div></section>}
  </div></Shell>;
}
